name: "Set up AWS CodeArtifact"
description: "Set up Code Artifact in NPM"
runs:
  using: "composite"
  steps:
    - run: |
        aws codeartifact login --tool npm --repository bhyve --domain gyg-internal-npm-repo
      shell: bash
