name: "Set up AWS Config"
description: ""
inputs:
  AWS_KEY:
    required: true
  AWS_SECRET:
    required: true
  AWS_REGION:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        aws configure set aws_access_key_id ${{ inputs.AWS_KEY }} --profile default
        aws configure set aws_secret_access_key ${{ inputs.AWS_SECRET }} --profile default
        aws configure set region ${{ inputs.AWS_REGION }} --profile default
      shell: bash
