name: "Get Environment Matrix"
description: "Provides JSON output of the matrix combination of gyg_env and gyg_region with AWS access keys"
outputs:
  matrix: # id of output
    description: "JSON format environment matrix output"
    value: ${{ steps.generate-matrix.outputs.matrix }}
runs:
  using: "composite"
  steps:
    - id: generate-matrix
      run: |
        cat << EOF > matrix.yaml
        gyg_env: [Dev, Staging]
        gyg_region: [Australia, USA]
        include:
        - gyg_env: Dev
          AWS_KEY: AWS_TEST_DEPLOY_KEY
          AWS_SECRET: AWS_TEST_DEPLOY_SECRET
          AWS_REGION: AWS_TEST_DEPLOY_REGION
        - gyg_env: Staging
          AWS_KEY: AWS_STAGING_DEPLOY_KEY
          AWS_SECRET: AWS_STAGING_DEPLOY_SECRET
          AWS_REGION: AWS_STAGING_DEPLOY_REGION
        EOF
        npm install -g yamljs
        matrix=$(yaml2json matrix.yaml)
        echo "::set-output name=matrix::$matrix"
      shell: bash
