name: "Release deploy"
description: "download packages and deploy"
inputs:
  gyg_env:
    required: true
  gyg_region:
    required: true
  version:
    required: true
  passphrase:
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        if [[ "${{ inputs.gyg_env }}" == "prod" ]];
        then 
          if ! [[ "${{ inputs.passphrase }}" == "${{ secrets.BHYVE_DEPLOY_PROD_PASSPHRASE }}" ]];
          then
            echo "Production deploy requires the correct passphrase to be entered."
            exit 1;
          fi
        fi
      shell: bash
    - run: |
        if ! [[ "${{ inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+[\-0-9a-zA-z\.]*$ ]];
        then
          echo "version needs to be of format v*.*.* where * is a digit. e.g. v0.3.2";
          echo "optionally version can have the branch suffixed v*.*.*-branch-name.0";
          exit 1;
        fi
      shell: bash
    - run: |
        echo ${{ github.token }} | gh auth login --with-token
        zipName="*-${{ inputs.gyg_env }}-${{ inputs.gyg_region }}-${{ inputs.version }}.zip"
        msg="Downloading artifact '$zipName' for deployment"
        echo $msg
        gh release download -p $zipName ${{ inputs.version }}
      shell: bash
    - env:
        GYG_ENV: ${{ inputs.gyg_env }}
        GYG_REGION: ${{ inputs.gyg_region }}
        RELEASE_VERSION: ${{ inputs.version }}
      run: |
        yarn release:diff || true
        yarn release:deploy
      shell: bash
    
