name: "Release deploy"
description: "download packages and deploy"
inputs:
  gyg_env:
    required: true
  gyg_region:
    required: true
  version:
    required: true
  slack_webhook:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        if ! [[ "${{ inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+[\-0-9a-zA-z\.]*$ ]];
        then
          echo "version needs to be of format v*.*.* where * is a digit. e.g. v0.3.2";
          echo "optionally version can have the branch suffixed v*.*.*-branch-name.0";
          exit 1;
        fi
      shell: bash
    - run: |
        echo ${{ github.token }} | gh auth login --with-token
        zipName="*-${{ inputs.gyg_env }}-${{ inputs.gyg_region }}-${{ inputs.version }}.zip"
        msg="Downloading artifact '$zipName' for deployment"
        echo $msg
        gh release download -p $zipName ${{ inputs.version }}
      shell: bash
    - env:
        GYG_ENV: ${{ inputs.gyg_env }}
        GYG_REGION: ${{ inputs.gyg_region }}
        RELEASE_VERSION: ${{ inputs.version }}
      run: |
        yarn release:diff || true
        yarn release:deploy
      shell: bash
    - name: Slack Notification
      uses: rtcamp/action-slack-notify@v2
      env:
          SLACK_CHANNEL: gyg
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: 'Deploying ${{ github.event.repository.name }} ${{ inputs.version }} to ${{ inputs.gyg_env }}_${{ inputs.gyg_region }}'
          SLACK_MESSAGE: 'Please check ${{ github.event.repository.name }} for new release version.'
          SLACK_USERNAME: Github
          SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
    
