name: "Release package"
description: "create and upload packages"
inputs:
  version:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        yarn release:build
      shell: bash
    - run: |
        echo ${{ github.token }} | gh auth login --with-token
        artifacts=*.zip; msg="Uploading $artifacts to release ${{ inputs.version }}"
        echo $msg
        gh release upload ${{ inputs.version }} *.zip
      shell: bash
