name: "Release package"
description: "create and upload packages"
runs:
  using: "composite"
  steps:
    - run: |
        yarn release:build
        gh release create ${{ github.ref }}
      shell: bash
    - run: |
        gh release upload ${{ github.ref }} *.zip
