name: "Release package"
description: "create and upload packages"
inputs:
  gyg_env:
    required: true
  gyg_region:
    required: true
  version:
    required: true
  branch:
    required: false
  working_directory:
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Modify version
      id: modify_version
      run: |
        modified_version=${{ inputs.version//\//-}}
        echo "::set-output name=modified_version::$modified_version"
      shell: bash
      working-directory: ${{ inputs.working_directory }}
    - env:
        GYG_ENV: ${{ inputs.gyg_env }}
        GYG_REGION: ${{ inputs.gyg_region }}
        RELEASE_VERSION: ${{ steps.modify_version.outputs.modified_version }}
        BRANCH: ${{ inputs.branch }}
      run: |
        yarn release:build
      shell: bash
      working-directory: ${{ inputs.working_directory }}
    - run: |
        echo ${{ github.token }} | gh auth login --with-token
        artifacts=*.zip; msg="Uploading $artifacts to release ${{ steps.modify_version.outputs.modified_version }}"
        echo $msg
        gh release upload ${{ steps.modify_version.outputs.modified_version }} *.zip
      shell: bash
      working-directory: ${{ inputs.working_directory }}
