name: "Release package"
description: "create and upload packages"
runs:
  using: "composite"
  steps:
    - run: |
        yarn release:build
      shell: bash
    - run: |
        echo ${{ github.token }} | gh auth login --with-token
        gh release upload ${{ github.ref }} *.zip
      shell: bash
