name: "Release package"
description: "create and upload packages"
inputs:
  gyg_env:
    required: true
  gyg_region:
    required: true
  version:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        [[ "${{ inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]
      shell: bash
    - env:
        GYG_ENV: ${{ inputs.gyg_env }}
        GYG_REGION: ${{ inputs.gyg_region }}
        RELEASE_VERSION: ${{ inputs.version }}
      run: |
        yarn release:build
      shell: bash
    - run: |
        echo ${{ github.token }} | gh auth login --with-token
        artifacts=*.zip; msg="Uploading $artifacts to release ${{ inputs.version }}"
        echo $msg
        gh release upload ${{ inputs.version }} *.zip
      shell: bash
