name: "Release package"
description: "create and upload packages"
inputs:
  gyg_env:
    required: true
  gyg_region:
    required: true
  version:
    required: true
  branch:
    required: false
  run_cmd:
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        if ! [[ "${{ inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+[\-0-9a-zA-z\.]*$ ]];
        then
          echo "version needs to be of format v*.*.* where * is a digit. e.g. v0.3.2";
          echo "optionally version can have the branch suffixed v*.*.*-branch-name.0";
          exit 1;
        fi
      shell: bash
    - env:
        GYG_ENV: ${{ inputs.gyg_env }}
        GYG_REGION: ${{ inputs.gyg_region }}
        RELEASE_VERSION: ${{ inputs.version }}
        BRANCH: ${{ inputs.branch }}
        BHYVE_DEVELOPER_NAME: sofy
      run: |
        if ! [[ $GYG_ENV == "test" ]]; then
          unset BHYVE_DEVELOPER_NAME
        fi
        RUN_CMD="${{ inputs.run_cmd }}"
        if [[ ${RUN_CMD+exists} == "" ]];
        then
          yarn release:build
        else
          ${{ inputs.run_cmd }}
        fi
      shell: bash
    - run: |
        echo ${{ github.token }} | gh auth login --with-token
        artifacts=*.zip; msg="Uploading $artifacts to release ${{ inputs.version }}"
        echo $msg
        gh release upload ${{ inputs.version }} *.zip
      shell: bash
