name: Setup Redis
description: Install Redis and export the server's host and port
runs:
  using: composite
  steps:
    - run: |
        sudo add-apt-repository ppa:redislabs/redis
        sudo apt-get update
        sudo apt-get install redis-server -y
        echo "host=localhost" >> $GITHUB_OUTPUT
        echo "port=6379" >> $GITHUB_OUTPUT
      shell: bash
outputs:
  host:
    description: Host the Redis server is running on
  port:
    description: Port the Redis server is running on
