name: "Setup MySQL"
description: ""
inputs:
  username:

    required: true
  password:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        sudo service mysql start
        mysql -u root --password=root -e "CREATE USER '${{ inputs.username }}'@'localhost' IDENTIFIED BY '${{ inputs.password }}';"
        mysql -u root --password=root -e "GRANT ALL PRIVILEGES ON * . * TO '${{ inputs.username }}'@'localhost';"
        mysql -u root --password=root -e "FLUSH PRIVILEGES;"
      shell: bash
