name: "Release Tag"
description: "tag a release"
inputs:
  version:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        [[ "${{ inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]
      shell: bash
    - run: |
        git tag ${{ inputs.version }}
        git push origin ${{ inputs.version }}
        echo ${{ github.token }} | gh auth login --with-token
        gh release create ${{ inputs.version }}
      shell: bash
