name: "Release Tag"
description: "tag a release"
inputs:
  version:
    required: true
outputs:
  version: # id of output
    description: "Version number output"
    value: ${{ steps.release-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - run: |
        echo "Releasing a '${{ inputs.version }}' version"
        if ! [[ "${{ inputs.version }}" =~ ^major|minor|patch$ ]]; 
        then
          echo "version needs to be: major OR minor OR patch";
          exit 1;
        fi
      shell: bash
    - id: release-version
      run: |
        yarn version --${{ inputs.version }}
        VERSION=`node -pe "require('./package.json').version"`
        echo "::set-output name=version::$(echo $VERSION)"
        git add .
        git commit -m "${{ inputs.message }}" || true
        git push
        git push origin $VERSION
        echo ${{ github.token }} | gh auth login --with-token
        gh release create $VERSION
      shell: bash
