name: "Release Tag"
description: "tag a release"
inputs:
  version:
    required: true
outputs:
  version: # id of output
    description: "Version number output"
    value: ${{ steps.release-version.outputs.version }}
runs:
  id: release-version
  using: "composite"
  steps:
    - run: |
        if ! [[ "${{ inputs.version }}" =~ "^major|minor|patch$" ]]; 
        then
          echo "version needs to be: major OR minor OR patch";
          exit 1;
        fi
      shell: bash
    - run: |
        yarn version --${{ inputs.version }}
        VERSION=`node -pe "require('./package.json').version"`
        echo "::set-output name=version::$(echo $VERSION)"
        git push origin $VERSION
        echo ${{ github.token }} | gh auth login --with-token
        gh release create $VERSION
      shell: bash
