name: Build, Lint, Test

on: [push, pull_request]

jobs:
    Build-Lint-Test:
        runs-on: ubuntu-latest

        steps:

            - name: Pin Node to 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Set up MySQL
              uses: guzmanygomez/github-actions/setup-mysql@main
              with:
                  username: gyg
                  password: gyg

         

        