name: Build, Lint, Test

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
    Build-Lint-Test:
        runs-on: ubuntu-latest

        steps:

            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch

            - name: Set up MySQL
              uses: guzmanygomez/github-actions/setup-mysql@${{ steps.extract_branch.outputs.branch }}
              with:
                  username: gyg
                  password: gyg

         

        