name: Build, Lint, Test

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
    Build-Lint-Test:
        runs-on: ubuntu-latest

        steps:

            - name: Extract branch name
              shell: bash
              run: echo ${GITHUB_REF##*/}
              id: extract_branch

            - name: Set up MySQL
              uses: guzmanygomez/github-actions/setup-mysql@main
              with:
                  username: gyg
                  password: gyg

         

        